Repository GnuCodingStudio/GameZam002-still-steal, pull requests merged in 2024-07, with the labels that each got.

#1 feat: Implement save/restore mechanism
  controller/save/ProgressionSave.gd
  controller/save/SaveController.gd
  project.godot
  scenes/MainMenu.gd
  scenes/MainMenu.tscn
  scenes/levels/BasicLevel.gd
  scripts/StartGameButton.gd
Labels: Type: Feature, Status: Awaiting Review

#2 Hotfix : Disable sound when player is disabled
  actors/Player.gd
  scenes/levels/BasicLevel.gd
  scenes/levels/Level_02.tscn
  scenes/levels/Level_05.tscn
Labels: Type: Bug, Status: Awaiting Review

#3 fix: Do not trigger failure mechanism if scene is already reloading
  scenes/levels/BasicLevel.gd
Labels: Type: Bug, Status: Awaiting Review

#4 feat: Implement Credits scene
  scenes/MainMenu.gd
  scenes/MainMenu.tscn
  scenes/credits/AssetsLink.gd
  scenes/credits/AssetsLink.tscn
  scenes/credits/Credits.gd
  scenes/credits/Credits.tscn
Labels: Type: Feature, Status: Awaiting Review

#9 ci: Setup export for Itchio
  README.md
  assets/images/Still-steal.jpg.import
  assets/images/Still-steal.png
  assets/images/Still-steal.png.import
  assets/release/cover.png
  assets/release/cover.png.import
  assets/release/itchio.png
  assets/release/itchio.png.import
  assets/release/screenshot-01.png
  assets/release/screenshot-01.png.import
  export_presets.cfg
  project.godot
Labels: Type: Feature, Status: Awaiting Review

#10 feat: door opening mechanism on level 5
  assets/audio/sfx/unlock-door.mp3
  assets/audio/sfx/unlock-door.mp3.import
  objects/EndGate.gd
  objects/EndGate.tscn
  res/Level.tres
  scenes/credits/Credits.tscn
  scenes/levels/BasicLevel.gd
  scenes/levels/Level_05.tscn
Labels: Type: Enhancement, Status: Awaiting Review
